import { describe, it, expect } from "vitest";
import { defineSchema, table, serial, text } from "neoorm/schema";
import { schemaToManifest, validateManifest } from "../src/codegen/schema-to-manifest.js";
import type { Manifest, ManifestTable } from "../src/dialect/types.js";
import { postgresDialect } from "../src/dialect/postgres.js";
import { dataToSqlValues, buildInsertQuery } from "../src/runtime/query/compile.js";
import { fillMissingPrimaryKeys } from "../src/runtime/query/primary-key.js";

function requireItemsTable(manifest: Manifest): ManifestTable {
  const items = manifest.tables.items;
  if (!items) {
    throw new Error("expected items table in manifest");
  }
  return items;
}

const schema = defineSchema({
  items: table("items", {
    id: serial().primary(),
    name: text().notNull(),
  }),
});

describe("serial column", () => {
  it("marks serial columns as generated in manifest", () => {
    const manifest = schemaToManifest(schema);
    expect(validateManifest(manifest)).toEqual([]);

    const items = requireItemsTable(manifest);
    const idCol = items.columns.find((c) => c.tsName === "id");
    expect(idCol?.kind).toBe("serial");
    expect(idCol?.generated).toBe(true);
    expect(idCol?.primary).toBe(true);
  });

  it("emits identity column SQL in DDL", () => {
    const manifest = schemaToManifest(schema);
    const items = requireItemsTable(manifest);
    const sql = postgresDialect.emitCreateTable(items);
    expect(sql).toContain(
      '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
    );
  });

  it("does not fill serial primary keys client-side", () => {
    const manifest = schemaToManifest(schema);
    const items = requireItemsTable(manifest);
    const data: Record<string, unknown> = { name: "Widget" };
    fillMissingPrimaryKeys(items, data);

    expect(data.id).toBeUndefined();
    expect(data.name).toBe("Widget");
  });

  it("omits serial primary key from insert when not provided", () => {
    const manifest = schemaToManifest(schema);
    const items = requireItemsTable(manifest);
    const { keys } = dataToSqlValues(items, { name: "Widget" });
    expect(keys).toEqual(["name"]);

    const sql = buildInsertQuery(items, keys);
    expect(sql).toMatch(/INSERT INTO "items" \("name"\) VALUES/);
    expect(sql).toContain("RETURNING");
    expect(sql).toContain('"id"');
  });
});
