import type { Manifest, ManifestColumn, ManifestRelation, ManifestTable } from "../dialect/types.js";
import { effectiveRelations, pascalCase } from "./manifest-relations.js";

function columnUnion(columns: ManifestColumn[]): string {
  if (columns.length === 0) return "never";
  return columns.map((c) => `"${c.tsName}"`).join(" | ");
}

function selectType(columns: ManifestColumn[]): string {
  const union = columnUnion(columns);
  const objectFields = columns.map((c) => `${c.tsName}?: true`).join("; ");
  return `readonly (${union})[] | { ${objectFields} }`;
}

function orderByType(columns: ManifestColumn[]): string {
  if (columns.length === 0) return "Record<string, never>";
  const fields = columns.map((c) => `${c.tsName}?: OrderDirection`).join("; ");
  return `{ ${fields} }`;
}

function emitRelationIncludeType(
  manifest: Manifest,
  tableAccessor: string,
  relation: ManifestRelation,
): string {
  const typeName = `${pascalCase(tableAccessor)}${pascalCase(relation.name)}Include`;
  const target = manifest.tables[relation.targetAccessor];
  const columns = target?.columns ?? [];
  const nestedWith = `${pascalCase(relation.targetAccessor)}With`;

  return `export type ${typeName} =
  | boolean
  | {
      select?: ${selectType(columns)};
      orderBy?: ${orderByType(columns)};
      limit?: number;
      with?: ${nestedWith};
    };`;
}

function emitTableWithType(
  manifest: Manifest,
  table: ManifestTable,
): string {
  const typeName = `${pascalCase(table.accessor)}With`;
  const relations = effectiveRelations(manifest, table);

  if (relations.length === 0) {
    return `export type ${typeName} = Record<string, never>;`;
  }

  const fields = relations
    .map((rel) => {
      const includeType = `${pascalCase(table.accessor)}${pascalCase(rel.name)}Include`;
      return `  ${rel.name}?: ${includeType};`;
    })
    .join("\n");

  return `export type ${typeName} = {\n${fields}\n};`;
}

export function emitIncludesTs(manifest: Manifest): string {
  const lines: string[] = [
    "// Auto-generated by neoorm generate — do not edit",
    `import type { OrderDirection } from "neoorm/schema";`,
    "",
  ];

  const tables = Object.values(manifest.tables).sort((a, b) =>
    a.accessor.localeCompare(b.accessor),
  );

  for (const table of tables) {
    for (const rel of effectiveRelations(manifest, table)) {
      lines.push(emitRelationIncludeType(manifest, table.accessor, rel));
      lines.push("");
    }
  }

  for (const table of tables) {
    lines.push(emitTableWithType(manifest, table));
    lines.push("");
  }

  const includeMapEntries = tables
    .map((t) => `  ${t.accessor}: ${pascalCase(t.accessor)}With;`)
    .join("\n");

  lines.push(`export type NeoOrmIncludes = {`);
  lines.push(includeMapEntries);
  lines.push(`};`);
  lines.push("");

  return lines.join("\n");
}
