import type {
	Manifest,
	ManifestColumn,
	ManifestRelation,
	ManifestTable,
} from "../dialect/types.js";
import {
	effectiveRelations,
	modelTypeName,
	pascalCase,
} from "./manifest-relations.js";

function columnUnion(columns: ManifestColumn[]): string {
	if (columns.length === 0) return "never";
	return columns.map((c) => `"${c.tsName}"`).join(" | ");
}

function selectType(columns: ManifestColumn[]): string {
	const union = columnUnion(columns);
	const objectFields = columns.map((c) => `${c.tsName}?: true`).join("; ");
	return `readonly (${union})[] | { ${objectFields} }`;
}

function orderByType(columns: ManifestColumn[]): string {
	if (columns.length === 0) return "Record<string, never>";
	const fields = columns
		.map((c) => `${c.tsName}?: OrderDirection`)
		.join("; ");
	return `{ ${fields} }`;
}

function emitRelationIncludeType(
	manifest: Manifest,
	tableAccessor: string,
	relation: ManifestRelation,
): string {
	const typeName = `${modelTypeName(tableAccessor)}${pascalCase(relation.name)}Include`;
	const target = manifest.tables[relation.targetAccessor];
	const columns = target?.columns ?? [];
	const nestedWith = `${modelTypeName(relation.targetAccessor)}With`;
	const targetWhere = `${modelTypeName(relation.targetAccessor)}Where`;

	return `export type ${typeName} =
  | boolean
  | {
      select?: ${selectType(columns)};
      where?: ${targetWhere};
      orderBy?: ${orderByType(columns)};
      take?: number;
      skip?: number;
      with?: ${nestedWith};
    };`;
}

function emitTableWithType(manifest: Manifest, table: ManifestTable): string {
	const typeName = `${modelTypeName(table.accessor)}With`;
	const relations = effectiveRelations(manifest, table);
	const manyRelations = relations.filter((rel) => rel.cardinality === "many");

	if (relations.length === 0) {
		return `export type ${typeName} = Record<string, never>;`;
	}

	const fields = relations
		.map((rel) => {
			const includeType = `${modelTypeName(table.accessor)}${pascalCase(rel.name)}Include`;
			return `  ${rel.name}?: ${includeType};`;
		})
		.join("\n");

	const countField =
		manyRelations.length > 0
			? `\n  _count?: {\n${manyRelations
					.map((rel) => {
						const targetWhere = `${modelTypeName(rel.targetAccessor)}Where`;
						return `    ${rel.name}?: true | { where?: ${targetWhere} };`;
					})
					.join("\n")}\n  };`
			: "";

	return `export type ${typeName} = {\n${fields}${countField}\n};`;
}

export function emitIncludesTs(manifest: Manifest): string {
	const tables = Object.values(manifest.tables).sort((a, b) =>
		a.accessor.localeCompare(b.accessor),
	);
	const withNames = tables.map((t) => `${modelTypeName(t.accessor)}With`);
	const whereNames = tables.map((t) => `${modelTypeName(t.accessor)}Where`);
	const lines: string[] = [
		"// Auto-generated by neoorm generate — do not edit",
		`import type { ${whereNames.join(", ")} } from "./query-types.js";`,
		"",
		`type OrderDirection = "asc" | "desc";`,
		"",
	];

	for (const table of tables) {
		for (const rel of effectiveRelations(manifest, table)) {
			lines.push(emitRelationIncludeType(manifest, table.accessor, rel));
			lines.push("");
		}
	}

	for (const table of tables) {
		lines.push(emitTableWithType(manifest, table));
		lines.push("");
	}

	const includeMapEntries = tables
		.map((t) => `  ${t.accessor}: ${modelTypeName(t.accessor)}With;`)
		.join("\n");

	lines.push(`export type NeoOrmIncludes = {`);
	lines.push(includeMapEntries);
	lines.push(`};`);
	lines.push("");

	void withNames;

	return lines.join("\n");
}
