import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, relative, dirname } from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import type { Manifest } from "../dialect/types.js";
import { postgresDialect } from "../dialect/postgres.js";
import { emitIncludesTs } from "./emit-includes.js";
import type { ManyToManyDef } from "../schema/many-to-many.js";

async function resolveManyToManyDefs(): Promise<ManyToManyDef[]> {
  const { getManyToManyRegistry } = await import("../schema/many-to-many.js");
  const fromDist = getManyToManyRegistry();
  if (fromDist.length > 0) {
    return [...fromDist];
  }

  // tsx path aliases may load schema DSL from src/ while codegen runs from dist/
  try {
    const codegenDir = dirname(fileURLToPath(import.meta.url));
    const { getManyToManyRegistry: getSrcRegistry } = await import(
      join(codegenDir, "../../src/schema/many-to-many.js")
    );
    const fromSrc = getSrcRegistry();
    if (fromSrc.length > 0) {
      return [...fromSrc];
    }
  } catch {
    // src/ not available in published package — dist registry is authoritative
  }

  return [];
}

export async function loadSchemaModule(schemaPath: string): Promise<{
  schema: import("../schema/define-schema.js").SchemaDef<Record<string, import("../schema/table.js").TableDef>>;
  manyToMany: ManyToManyDef[];
}> {
  const { pathToFileURL } = await import("node:url");
  const { register } = await import("tsx/esm/api");
  const { clearManyToManyRegistry } = await import("../schema/many-to-many.js");

  register();
  clearManyToManyRegistry();

  const url = pathToFileURL(schemaPath).href;
  const mod = await import(url);

  const schema = mod.schema ?? mod.default?.schema ?? mod.default;
  if (!schema || !schema._tables) {
    throw new Error(
      `Schema file must export a schema via \`export const schema = defineSchema(...)\``,
    );
  }

  const manyToMany = await resolveManyToManyDefs();

  return { schema, manyToMany };
}

export function hashManifest(manifest: Manifest): string {
  return createHash("sha256")
    .update(JSON.stringify(manifest))
    .digest("hex")
    .slice(0, 16);
}

export async function readSnapshot(outDir: string): Promise<Manifest | null> {
  try {
    const content = await readFile(join(outDir, "snapshot.json"), "utf-8");
    return JSON.parse(content) as Manifest;
  } catch {
    return null;
  }
}

export async function writeSnapshot(
  outDir: string,
  manifest: Manifest,
): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await writeFile(
    join(outDir, "snapshot.json"),
    JSON.stringify(manifest, null, 2),
    "utf-8",
  );
}

export function emitManifestTs(manifest: Manifest, packageImportPath: string): string {
  return `// Auto-generated by neoorm generate — do not edit
import type { Manifest } from "${packageImportPath}";

export const manifest = ${JSON.stringify(manifest, null, 2)} as const satisfies Manifest;
`;
}

export function emitClientTs(schemaImportPath: string, packageImportPath: string): string {
  return `// Auto-generated by neoorm generate — do not edit
import { createNeoOrmClient } from "${packageImportPath}";
import type { TypedNeoOrmClient } from "${packageImportPath}";
import { manifest } from "./manifest.js";
import { schema } from "${schemaImportPath}";
import type { NeoOrmIncludes } from "./includes.js";

export const db: TypedNeoOrmClient<typeof schema._tables, NeoOrmIncludes> =
  createNeoOrmClient<typeof schema._tables, NeoOrmIncludes>(manifest);
`;
}

function toImportPath(fromDir: string, toFile: string): string {
  let importPath = relative(fromDir, toFile).replace(/\\/g, "/");
  if (!importPath.startsWith(".")) {
    importPath = `./${importPath}`;
  }
  return importPath.replace(/\.ts$/, ".js");
}

function schemaImportPath(outDir: string, schemaPath: string): string {
  return toImportPath(outDir, schemaPath);
}

function packageImportPath(outDir: string, projectRoot: string): string {
  return toImportPath(outDir, join(projectRoot, "dist/index.js"));
}

export function diffManifest(
  prev: Manifest | null,
  next: Manifest,
): { isInitial: boolean; sql: string[] } {
  if (!prev) {
    const sql = Object.values(next.tables).map((t) =>
      postgresDialect.emitCreateTable(t),
    );
    return { isInitial: true, sql };
  }

  const sql: string[] = [];
  const prevTables = new Set(Object.keys(prev.tables));
  const nextTables = new Set(Object.keys(next.tables));

  for (const accessor of nextTables) {
    if (!prevTables.has(accessor)) {
      const table = next.tables[accessor]!;
      sql.push(postgresDialect.emitCreateTable(table));
    } else {
      const prevTable = prev.tables[accessor]!;
      const nextTable = next.tables[accessor]!;
      const prevCols = new Set(prevTable.columns.map((c) => c.sqlName));
      const addColumns = nextTable.columns.filter(
        (c) => !prevCols.has(c.sqlName),
      );
      if (addColumns.length > 0) {
        sql.push(
          ...postgresDialect.emitAlterTable(nextTable, { addColumns }),
        );
      }
    }
  }

  return { isInitial: false, sql };
}

export async function writeMigration(
  outDir: string,
  sql: string[],
  name?: string,
): Promise<string | null> {
  if (sql.length === 0) return null;

  const migrationsDir = join(outDir, "migrations");
  await mkdir(migrationsDir, { recursive: true });

  const timestamp = new Date()
    .toISOString()
    .replace(/[-:T.Z]/g, "")
    .slice(0, 14);
  const migrationName = name ?? `${timestamp}_migration`;
  const migrationDir = join(migrationsDir, migrationName);
  await mkdir(migrationDir, { recursive: true });
  await writeFile(join(migrationDir, "migration.sql"), sql.join("\n\n"), "utf-8");

  return migrationName;
}

export async function writeGeneratedFiles(
  outDir: string,
  manifest: Manifest,
  migrationSql: string[],
  schemaPath: string,
  projectRoot: string,
): Promise<{ migrationName: string | null }> {
  await mkdir(outDir, { recursive: true });
  await writeFile(
    join(outDir, "manifest.ts"),
    emitManifestTs(manifest, packageImportPath(outDir, projectRoot)),
    "utf-8",
  );
  await writeFile(
    join(outDir, "includes.ts"),
    emitIncludesTs(manifest),
    "utf-8",
  );
  await writeFile(
    join(outDir, "client.ts"),
    emitClientTs(
      schemaImportPath(outDir, schemaPath),
      packageImportPath(outDir, projectRoot),
    ),
    "utf-8",
  );
  await writeSnapshot(outDir, manifest);

  const migrationName = await writeMigration(outDir, migrationSql);

  return { migrationName };
}

export async function generateFromSchema(
  schemaPath: string,
  outDir: string,
  projectRoot?: string,
): Promise<{ manifest: Manifest; migrationName: string | null }> {
  const { schemaToManifest, validateManifest } = await import(
    "./schema-to-manifest.js"
  );

  const { schema, manyToMany } = await loadSchemaModule(schemaPath);
  const manifest = schemaToManifest(schema, manyToMany);

  const errors = validateManifest(manifest);
  if (errors.length > 0) {
    throw new Error(`Schema validation failed:\n${errors.join("\n")}`);
  }

  const prev = await readSnapshot(outDir);
  const { sql } = diffManifest(prev, manifest);
  const root = projectRoot ?? process.cwd();
  const { migrationName } = await writeGeneratedFiles(outDir, manifest, sql, schemaPath, root);

  return { manifest, migrationName };
}
