// Auto-generated by neoorm generate — do not edit
import { createNeoOrmClient } from "neoorm";
import type { TypedNeoOrmClient } from "neoorm";
import { manifest } from "./manifest.js";
import { schema } from "./schema.js";
import type { NeoOrmIncludes } from "./includes.js";
import type { NeoOrmRowPayloads } from "./models.js";

export const db: TypedNeoOrmClient<
  typeof schema._tables,
  NeoOrmIncludes,
  NeoOrmRowPayloads
> = createNeoOrmClient<
  typeof schema._tables,
  NeoOrmIncludes,
  NeoOrmRowPayloads
>(manifest);

export type * from "./models.js";
export type * from "./includes.js";
