// Auto-generated by neoorm generate — do not edit
import type { OrderDirection } from "neoorm/schema";

export type UsersWith = Record<string, never>;

export type NeoOrmIncludes = {
  users: UsersWith;
};
