// Auto-generated by neoorm generate — do not edit
import type { UsersWith } from "./includes.js";

type IncludeRelation<
  W,
  Key extends PropertyKey,
  Cardinality extends "one" | "many",
  TModel,
> = W extends { [K in Key]?: unknown }
  ? Cardinality extends "many"
    ? { [P in Key]: TModel[] }
    : { [P in Key]: TModel | null }
  : {};

export type User = {
  id: string;
  emailAddress: string;
};

export type UserPayload = User;

export type UserWithIncludes<W extends UsersWith | undefined = undefined> = User;

export type NeoOrmModels = {
  users: User;
};

export type NeoOrmRowPayloads = {
  users: UserPayload;
};

export type NeoOrmResultAt<
  K extends keyof NeoOrmModels,
  W,
> =
  K extends "users" ? UserWithIncludes<
    W extends UsersWith | undefined ? W : undefined
  >
  : never;
