/**
 * @packageDocumentation
 * NeoOrm schema DSL — define tables, columns, foreign keys, and relations.
 *
 * Import from `neoorm/schema` when authoring `schema.ts`.
 */
export type {
	DecimalOptions,
	EnumTypeOptions,
	UuidOptions,
} from "../plugins/builtin.js";
export type {
	ColumnBuilder,
	ColumnKind,
	ColumnMeta,
	TimestampColumnBuilder,
} from "./column.js";
export {
	bigint,
	bool,
	bytea,
	citext,
	decimal,
	enumType,
	id,
	int,
	intArray,
	json,
	jsonb,
	numeric,
	serial,
	text,
	textArray,
	timestamp,
	timestamps,
	uuid,
} from "./column.js";
export type { SchemaDef, SchemaOptions } from "./define-schema.js";
export { defineSchema } from "./define-schema.js";
export type {
	InlineManyToManyOptions,
	ManyToManyExtra,
} from "./many-to-many.js";
export { many, manyToMany } from "./many-to-many.js";
export { clearTableRegistry } from "./table-registry.js";
export type {
	FkBuilder,
	FkMeta,
	OnDeleteAction,
} from "./relation.js";
export { fk } from "./relation.js";
export type {
	InlineM2MInverseRelations,
	InlineM2MInverseWhereMap,
	InlineM2MInverseWriteMap,
	InlineM2MRelations,
	InlineM2MWhereMap,
	InlineM2MWriteMap,
	InverseRelations,
	JunctionM2MRelations,
	NestedCreateInput,
	OutgoingFkRelations,
	RelationCreateMap,
	RelationUpdateMap,
	SqlNameToAccessor,
} from "./relation-types.js";
export type {
	ColumnDef,
	ColumnNaming,
	ColumnRefs,
	IndexDef,
	IndexWherePredicate,
	PrimaryKeyDef,
	ScalarColumnKeys,
	TableDef,
	TableExtra,
	TableOptions,
} from "./table.js";
export { index, primaryKey, table, unique } from "./table.js";
export type {
	AggregateArgs,
	ApplyOmit,
	ApplySelect,
	ColumnWhereInput,
	ConnectInput,
	ConnectOrCreateItem,
	CountArgs,
	CountSelect,
	CreateArgs,
	CreateInput,
	CreateManyAndReturnArgs,
	CreateManyArgs,
	CreateManyInput,
	CursorInput,
	DeleteArgs,
	DeleteManyAndReturnArgs,
	DeleteManyArgs,
	ExistsArgs,
	FindByIdArgs,
	FindFirstArgs,
	FindManyArgs,
	FindOrCreateArgs,
	FindOrCreateResult,
	FindUniqueArgs,
	GroupByArgs,
	GroupByHaving,
	GroupByOrderBy,
	InferAggregateResult,
	InferCountResult,
	InferFindResult,
	InferGroupByResult,
	InferInsertRow,
	InferSelectRow,
	InferWithResult,
	LogicalWhereInput,
	ManyRelationFilter,
	NumericHaving,
	NumericUpdateOps,
	OmitInput,
	OrderByInput,
	OrderDirection,
	PaginateArgs,
	PaginateResult,
	QueryMode,
	RelationAccessors,
	RelationCountInput,
	RelationWhereMap,
	RelationWriteInput,
	ScalarPkName,
	ScalarSetOp,
	SchemaTables,
	SelectInput,
	HiddenKeys,
	StripOmitKeys,
	StripResult,
	StripCapable,
	UpdateArgs,
	UpdateInput,
	UpdateManyAndReturnArgs,
	UpdateManyArgs,
	UpsertArgs,
	WhereInput,
	WhereOperators,
	WithInclude,
	WithInput,
	WithInputMap,
	WithRelationOptions,
} from "./types.js";
